//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Grade = new HashSet<Grade>();
            this.StudentCourse = new HashSet<StudentCourse>();
        }
    
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Grade> Grade { get; set; }
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
    }
}
